version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: coding_judge_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coding_judge
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


  # 5432:5432